services:
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5000:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
  af: 
    container_name: airflow
    image: apache/airflow:latest
    ports: 
      - 8000:800
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
